# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  port: <%= ENV['DATABASE_PORT'] || 5432 %>


development:
  <<: *default
  database: CATALY_development

test:
  <<: *default
  database: CATALY_test
production:
  #以下、heroku練習用_datebaseのコメントアウトもherokuを実行するためにコメントアウトした。
  #database: db/production.sqlite3
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
